# ===========================================
# EKKLE SALES OS - PR Check
# Validação de Pull Requests
# ===========================================

name: PR Check

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  # ===========================================
  # Validação de código
  # ===========================================
  validate:
    name: Validate PR
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Type check
        run: bun tsc --noEmit

      - name: Run tests
        run: bun test
        continue-on-error: true

      - name: Check build
        run: |
          echo "Verificando se o build funciona..."
          bun build ./src/index.ts --outdir ./dist --target bun
          echo "✅ Build OK"
